USE DB_Bijuteria_Dona_Elvira;

INSERT INTO TAB_AUX_pessoa (primeiro_nome, segundo_nome, terceiro_nome, quarto_nome)
VALUES
    ('João', 'Pedro', 'Silva', 'Santos'),
    ('Maria', 'Clara', 'Oliveira', 'Pereira'),
    ('Carlos', 'Eduardo', 'Mendes', 'Gomes'),
    ('Ana', 'Luísa', 'Almeida', 'Fernandes'),
    ('Paulo', 'Roberto', 'Barbosa', 'Lima'),
    ('Fernanda', 'Cristina', 'Ribeiro', 'Martins'),
    ('José', 'Antonio', 'Costa', 'Sousa'),
    ('Mariana', 'Beatriz', 'Dias', 'Rocha'),
    ('Ricardo', 'Alexandre', 'Nogueira', 'Carvalho'),
    ('Luciana', 'Fernandes', 'Teixeira', 'Vieira'),
    ('Pedro', 'Henrique', 'Ferreira', 'Azevedo'),
    ('Juliana', 'Santos', 'Moreira', 'Correia'),
    ('Rafael', 'Rodrigues', 'Gonçalves', 'Melo'),
    ('Isabela', 'Freitas', 'Lopes', 'Moura'),
    ('Tiago', 'Felipe', 'Moraes', 'Silveira'),
    ('Camila', 'Fernanda', 'Pires', 'Ramos'),
    ('Gabriel', 'Duarte', 'Vieira', 'Santos'),
    ('Lorena', 'Sophia', 'Nunes', 'Silva'),
    ('Gustavo', 'Lucas', 'Carvalho', 'Martins'),
    ('Aline', 'Carolina', 'Lima', 'Alves'),
    ('Daniel', 'Oliveira', NULL, 'Pereira'),
    ('Beatriz', 'Macedo', NULL, 'Teixeira'),
    ('Liliana', 'de', 'Oliveira', 'Pratas'),
    ('Francisco', 'Rafael', 'Santos', 'Casado');
    
-- ACABAR 
INSERT INTO TAB_AUX_cargos_profissoes (ID_cargo, ID_profissao)
VALUES
	(2, ),
    (3, ),
    (4, ),
    (5, ),
    (6, ),
    (7, ),
    (8, ),
    (9, ),
    (10, ),
    (11, ),
    (12, ),
    (13, ),
    (14, ),
    (15, ),
    (16, ),
    (17, ),
    (18, ),
    (19, ),
    (20, ),
    (21, ),
    (22, ),
    (23, ),
    (24, ),
    (25, ),
    (26, ),
    (27, ),
    (28, );
