USE DB_Bijuteria_Dona_Elvira;

call ExecutarInsercaoRegistosMultiplosPessoas(1000);
call ExecutarInsercaoRegistosMultiplosClientes(500);
call ExecutarInsercaoRegistosMultiplosFuncionarios(50);
call ExecutarInsercaoRegistosMultiplosCidadoes(10);
call ExecutarInsercaoRegistosMultiplosEstrangeiros(10);
call ExecutarInsercaoRegistosMultiplosContratosAtuaisFuncionarios();
call ExecutarInsercaoRegistosMultiplasPromocoes();
call ExecutarInsercaoRegistosMultiplasAbastecimentosStock(NULL);